name: apache-beam-exploration
platforms:
  - linux-64
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.11.0
  - pip
  - geopandas
  - fsspec
  - requests
  - aiohttp
  - gdal

  - pip:
    - apache-beam
